apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod01
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-secret02
            key: userid
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret02
            key: password
